---
name: FlashCore
version: 1.0.3
main: DavidFlash\LobbyCore\Main
api: 3.14.0
commands:
  lobby:
     description: Teleports you to the main hub
  hub:
     description: Teleports you to the main hub
  flashcore:
     description: FlashCore Plugin Help
  fly:
     permission: fc.fly
     description: "Allow you to fly or a person."
permissions:
   fc.fly:
      description: "/fly permission"
      default: op 
...
