---
name: FlashCore
version: 1.0.7
main: DavidFlash\LobbyCore\Main
api: 3.14.0
protocol:
- 407
commands:
  lobby:
     description: Teleports you to the main hub
  hub:
     description: Teleports you to the main hub
  flashcore:
     description: FlashCore Plugin Help
  fly:
     permission: fc.fly
     description: Allow you to fly or a person to fly
  vanish:
     permission: fc.vanish
     description: Enables Vanish for you or other people
  freeze:
     permission: fc.freeze
     description: Freeze player when he's not kind
  haf:
     permission: fc.haf
     description: Fully restores your hunger and heal
  infoui:
     description: "Opens Server InfoUI"
permissions:
   fc.fly:
      description: "/fly permission"
      default: op 
   fc.vanish:
      description: "/vanish permission"
      default: op
   fc.freeze:
      description: "/freeze permission"
      default: op
   fc.haf:
      description: "/haf permission"
      default: op
...
