# LobbyCore by David Flash Configuration File
# Version 1.0.7

# Custom Settings


# LOBBY 


# The world where the Lobby is (NOTICE! The world needs to be loaded!)
world: "Lobby"

# Message that will be sent to players chat
message: "§f[§gFlash§fCore] §aYou were teleported to §fLobby!"

# Messages that will appear on players screen
title: "§cTeleporting.."
subtitle: "§fTo Hub"

# What gamemode will be applied when you do /hub (NEEDS TO BE NUMERIC)
gamemode: 2

# Item on lobby (REQUIRES PLUGIN FlashItem)
# These needs to be same as in FlashItem [true / false]
enabled-item: true

item: 345 # Default 345
name: "§l§aNavigator" # Deafult "§l§aNavigator"



# INFOUI

# Do you want to enable this feature? (true / false)

enabled: true

# What message should appear in InfoUI (Use \n for line break)

text: "Put what text you want here \n in config.yml!"